version: '3'
services:
  mongo-express:
    image: mongo-express
    ports:
      - 8080:8081
    networks:
      - mongo-compose-network
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: on-failure
  mongodb:
    image: mongo
    ports:
      - 27019:27019
    networks:
      - mongo-compose-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=gym
networks:
  mongo-compose-network:
    driver: bridge
